import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { adminFeedback, adminReviews, deleteCatalog, listCatalog, saveCatalog, verifyBusiness } from '../services/catalogService';
import { deleteReview } from '../services/reviewsService';
import { PlaceDetail, PlaceKind, Review } from '../types';
import { ErrorState, LoadingState } from '../components/StateViews';
export function AdminPage({section='dashboard'}:{section?:string}){return <section><h1>Admin {section==='dashboard'?'dashboard':section}</h1><nav className="admin-nav"><Link to="/admin">Overview</Link><Link to="/admin/places">Places</Link><Link to="/admin/businesses">Businesses</Link><Link to="/admin/reviews">Reviews</Link><Link to="/admin/feedback">Feedback</Link></nav>{section==='dashboard'?<Dashboard/>:section==='places'?<Catalog kind="place"/>:section==='businesses'?<Catalog kind="business"/>:section==='reviews'?<ReviewAdmin/>:<Feedback/>}</section>}
function Dashboard(){const [counts,setCounts]=useState<any>(null);useEffect(()=>{Promise.all([listCatalog('place'),listCatalog('business'),adminReviews(),adminFeedback()]).then(([p,b,r,f])=>setCounts({places:p.length,businesses:b.length,reviews:r.length,feedback:f.length}))},[]);if(!counts)return <LoadingState label="Loading dashboard…"/>;return <div className="stat-grid">{Object.entries(counts).map(([k,v])=><div className="stat" key={k}><strong>{String(v)}</strong><span>{k}</span></div>)}</div>}
const blank={name:'',category:'Culture',description:'',latitude:0,longitude:0,address:'',openTime:'09:00',closeTime:'18:00',costLevel:1,rating:0,ratingCount:0,sustainability:.5,verified:false};
function Catalog({kind}:{kind:PlaceKind}){const [rows,setRows]=useState<PlaceDetail[]|null>(null);const [form,setForm]=useState<any>(blank);const [edit,setEdit]=useState<string|undefined>();const [error,setError]=useState<string|null>(null);const load=()=>listCatalog(kind).then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[kind]);const submit=async(e:FormEvent)=>{e.preventDefault();setError(null);try{await saveCatalog(kind,{...form,category:[form.category],latitude:+form.latitude,longitude:+form.longitude,costLevel:+form.costLevel,sustainability:+form.sustainability},edit);setForm(blank);setEdit(undefined);load()}catch(x:any){setError(x.message)}};return <>{error&&<ErrorState message={error}/>}<form className="admin-form" onSubmit={submit}><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input required type="number" step="any" placeholder="Latitude" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/><input required type="number" step="any" placeholder="Longitude" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/><input placeholder="Address" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/><button className="btn">{edit?'Update':'Create'} {kind}</button></form>{!rows?<LoadingState label="Loading listings…"/>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Category</th><th>Verified</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x._id}><td>{x.name}</td><td>{x.category.join(', ')}</td><td>{x.verified?'Yes':'No'}</td><td><button onClick={()=>{setEdit(x._id);setForm({...x,category:x.category[0]||''})}}>Edit</button>{kind==='business'&&<button onClick={async()=>{await verifyBusiness(x._id,!x.verified);load()}}>{x.verified?'Unverify':'Verify'}</button>}<button onClick={async()=>{if(confirm(`Delete ${x.name}?`)){await deleteCatalog(kind,x._id);load()}}}>Delete</button></td></tr>)}</tbody></table></div>}</>}
function ReviewAdmin(){const [rows,setRows]=useState<Review[]|null>(null);const load=()=>adminReviews().then(setRows);useEffect(()=>{void load()},[]);return !rows?<LoadingState label="Loading reviews…"/>:<div className="table-wrap"><table><tbody>{rows.map(r=><tr key={r._id}><td>{r.rating}★</td><td>{r.comment}</td><td><button onClick={async()=>{await deleteReview(r._id);load()}}>Delete</button></td></tr>)}</tbody></table></div>}
function Feedback(){const [rows,setRows]=useState<any[]|null>(null);useEffect(()=>{adminFeedback().then(setRows)},[]);return !rows?<LoadingState label="Loading feedback…"/>:<div className="table-wrap"><table><tbody>{rows.map(r=><tr key={r._id}><td>{r.user?.name||'User'}</td><td>{r.targetType}</td><td>{r.useful?'Useful':'Not useful'}</td><td>{r.scadeScoreAtFeedback}%</td></tr>)}</tbody></table></div>}
