import { useEffect, useState } from 'react';
import { CATEGORIES, UserPreferences } from '../types';
import { createItinerary, deleteItinerary, Itinerary, listItineraries } from '../services/itinerariesService';
import { getMyPreferences } from '../services/preferencesService';
import { useGeolocation } from '../hooks/useGeolocation';
import { ErrorState, LoadingState, EmptyState } from '../components/StateViews';
const defaults:UserPreferences={interests:[],travelMode:'walking',availableTimeMin:180,budget:3,sustainabilityPreference:.5};
export function ItineraryPage(){const geo=useGeolocation();const [p,setP]=useState(defaults);const [title,setTitle]=useState('My day out');const [trips,setTrips]=useState<Itinerary[]|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const load=()=>listItineraries().then(setTrips).catch(e=>setError(e.message));useEffect(()=>{geo.locate();getMyPreferences().then(x=>setP({...defaults,...x}));load()},[]);// eslint-disable-line
const generate=async()=>{if(geo.latitude==null||geo.longitude==null){setError('Allow location access to choose a starting point.');return}setBusy(true);setError(null);try{await createItinerary({...p,title,startLat:geo.latitude,startLng:geo.longitude});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
return <section><h1>Itinerary planner</h1>{error&&<ErrorState message={error}/>}<div className="filter-panel"><label>Trip title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Available minutes<input type="number" min={15} value={p.availableTimeMin} onChange={e=>setP({...p,availableTimeMin:+e.target.value})}/></label><label>Travel mode<select value={p.travelMode} onChange={e=>setP({...p,travelMode:e.target.value as any})}><option value="walking">Walking</option><option value="cycling">Cycling</option><option value="driving">Driving</option><option value="public_transport">Public transport</option></select></label><label>Budget<select value={p.budget} onChange={e=>setP({...p,budget:+e.target.value})}><option value={0}>Free</option><option value={1}>Low</option><option value={2}>Medium</option><option value={3}>Any</option></select></label></div><div className="row">{CATEGORIES.map(c=><button key={c} className={`pill-btn ${p.interests.includes(c)?'active':''}`} onClick={()=>setP({...p,interests:p.interests.includes(c)?p.interests.filter(x=>x!==c):[...p.interests,c]})}>{c}</button>)}</div><p><button className="btn" disabled={busy||geo.status==='locating'} onClick={generate}>{busy?'Generating…':'Generate and save itinerary'}</button></p><h2>My trips</h2>{trips===null?<LoadingState label="Loading trips…"/>:trips.length===0?<EmptyState message="You have no saved trips yet."/>:trips.map(t=><article className="panel" key={t._id}><div className="spread"><h3>{t.title}</h3><button className="btn ghost" onClick={async()=>{await deleteItinerary(t._id);load()}}>Delete</button></div><p>{t.travelMode.replace('_',' ')} · {t.totalMinutesUsed}/{t.availableTimeMin} min</p><ol>{t.stops.map((s,i)=><li key={`${s.targetId}-${i}`}><b>{s.name}</b> — arrive +{s.arrivalOffsetMin} min, travel {s.travelMinFromPrev} min, visit {s.visitDurationMin} min</li>)}</ol>{t.stops.length===0&&<p>No platform listings fit the selected constraints.</p>}</article>)}</section>}
